Repository codevise/pageflow, pull requests merged in 2018-07, with the labels that each got.

#965 Improve tracking of visited pages
  app/assets/javascripts/pageflow/ready.js
  app/assets/javascripts/pageflow/visited.js
  app/views/pageflow/entries/show.html.erb
  spec/javascripts/pageflow/visited_spec.js
Labels: bug

#971 Fix page transition effects in Chrome 66 and above
  app/assets/stylesheets/pageflow/page_transitions/fade.scss
  app/assets/stylesheets/pageflow/page_transitions/fade_to_black.scss
  app/assets/stylesheets/pageflow/slideshow.scss
  app/assets/stylesheets/pageflow/themes/default/player_controls/slim/container.scss
Labels: bug

#932 Devise 4.4.0
  admins/pageflow/user.rb
  lib/generators/pageflow/resque/resque_generator.rb
  lib/generators/pageflow/resque/templates/devise_async.rb
  lib/pageflow/user_mixin.rb
  pageflow.gemspec
  spec/controllers/admin/accounts_controller_spec.rb
  spec/controllers/admin/any_controller_spec.rb
  spec/controllers/admin/entries_controller_spec.rb
  spec/controllers/admin/folders_controller_spec.rb
  spec/controllers/admin/memberships_controller_spec.rb
  spec/controllers/admin/revisions_controller_spec.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/pageflow/chapters_controller_spec.rb
  spec/controllers/pageflow/edit_locks_controller_spec.rb
  spec/controllers/pageflow/editor/encoding_confirmations_controller_spec.rb
  spec/controllers/pageflow/editor/entries_controller_spec.rb
  spec/controllers/pageflow/editor/entry_publications_controller_spec.rb
  spec/controllers/pageflow/editor/files_controller_spec.rb
  spec/controllers/pageflow/editor/widgets_controller_spec.rb
  spec/controllers/pageflow/entries_controller_spec.rb
  spec/controllers/pageflow/pages_controller_spec.rb
  spec/controllers/pageflow/revisions_controller_spec.rb
  spec/controllers/pageflow/storylines_controller_spec.rb
  spec/generators/pageflow/resque/resque_generator_spec.rb
  spec/support/config/devise.rb
  spec/views/components/pageflow/admin/user_accounts_tab_spec.rb
  spec/views/components/pageflow/admin/user_entries_tab_spec.rb
Labels: manual update step

#975 Consolidate migrations
  .rubocop.yml
  db/migrate/20140418225525_setup_schema.rb
  db/migrate/20140418240000_add_attributes_to_users.rb
  db/migrate/20140624135420_create_themings.rb
  db/migrate/20140624135421_create_themings_for_existing_accounts.rb
  db/migrate/20140624135422_change_theme_references_to_theming_references.rb
  db/migrate/20140624135423_remove_attributes_from_themes.rb
  db/migrate/20140624135424_create_accounts_themes_join_table.rb
  db/migrate/20140624135425_move_cname_from_account_to_theming.rb
  db/migrate/20140625184800_drop_themes.rb
  db/migrate/20140704110631_add_confirmed_by_to_encoded_files.rb
  db/migrate/20140819081454_add_home_url_attributes_to_themings_and_revisions.rb
  db/migrate/20141027102310_create_widgets.rb
  db/migrate/20141028125408_add_emphasize_chapter_beginning_to_revisions.rb
  db/migrate/20141119164526_add_emphasize_new_pages_to_revisions.rb
  db/migrate/20141119174032_add_sharing_image_to_revisions.rb
  db/migrate/20141128150305_add_locale_to_users.rb
  db/migrate/20141208161030_add_locale_to_revisions.rb
  db/migrate/20141211110226_add_configuration_to_chapters.rb
  db/migrate/20150115175116_add_features_configuration_to_accounts.rb
  db/migrate/20150115175207_add_features_configuration_to_entries.rb
  db/migrate/20150603091823_add_password_attributes_to_revisions.rb
  db/migrate/20150825133449_update_audio_loop_pages_to_use_atmo.rb
  db/migrate/20150826125417_create_pageflow_storylines.rb
  db/migrate/20150826125744_add_storyline_id_to_chapters.rb
  db/migrate/20150826125745_insert_main_storylines.rb
  db/migrate/20150830105831_remove_revision_id_from_chapters.rb
  db/migrate/20150830110006_remove_entry_id_from_chapters.rb
  db/migrate/20151022080518_add_first_published_at_to_entries.rb
  db/migrate/20160131222203_add_cache_counters.rb
  db/migrate/20160201130118_add_additional_cnames_to_themings.rb
  db/migrate/20160216130336_add_meta_fields_to_revision.rb
  db/migrate/20160225075853_add_overview_button_enabled_to_revisions.rb
  db/migrate/20160304072911_rename_membership_entry_and_make_polymorphic.rb
  db/migrate/20160304151327_add_role_to_membership.rb
  db/migrate/20160310080213_add_edited_at_to_entries.rb
  db/migrate/20160425192648_add_index_for_revision_publication_timestamps.rb
  db/migrate/20160504093145_replace_role_and_account_on_user.rb
  db/migrate/20160531152500_update_users_count.rb
  db/migrate/20160617123557_add_meta_fields_to_theming.rb
  db/migrate/20160707125400_add_output_presences_to_video_files.rb
  db/migrate/20160715105408_add_share_url_to_revisions.rb
  db/migrate/20160824115000_add_parent_file_to_video_files.rb
  db/migrate/20160824115100_add_parent_file_to_audio_files.rb
  db/migrate/20160824115200_add_parent_file_to_image_files.rb
  db/migrate/20160929102700_add_configuration_to_files.rb
  db/migrate/20161007144500_add_text_track_files.rb
  db/migrate/20161216175734_move_configuration_from_file_to_file_usage.rb
  db/migrate/20161230144429_add_processed_attachment_to_text_track_files.rb
  db/migrate/20170201074328_add_configuration_to_widgets.rb
  db/migrate/20170222124848_update_video_file_output_presences.rb
  db/migrate/20170315130000_add_theme_name_to_revisions.rb
  db/migrate/20170421112300_turn_background_video_pages_into_background_image_pages.rb
  db/migrate/20170912165050_reset_copied_snapshot_type.rb
  db/migrate/20170913105048_fix_hls_output_presences_for_legacy_video_files.rb
Labels: breaking change

#981 Migrate to state_machines gem
  Gemfile
  README.md
  app/controllers/pageflow/application_controller.rb
  lib/pageflow/engine.rb
  pageflow.gemspec
Labels: breaking change
